---
- include_vars: '{{ ansible_os_family }}.yml'
- include: install.yml
- include: server_config.yml
- include: vhosts_config.yml

- meta: flush_handlers

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
# vim:ft=ansible:
